name: 'dbt_olist_week3'
version: '1.0'
config-version: 2

profile: 'snowflake'

model-paths: ['models']
snapshot-paths: ['snapshots']

models:
  dbt_olist_week3:
    staging:
      # +schema: STG
    marts:
      +schema: MART

snapshots:
  +schema: SNAPSHOTS
